[build-system]
requires = [ 'setuptools>=64', 'setuptools_scm>=8', ]
build-backend = "setuptools.build_meta"

[project]
name = "BindControl"
dynamic = ['version']
dependencies = [
    'wx',
]

[tool.setuptools]
include-package-data = true

[tool.setuptools_scm]
